# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68dfe318383a8a7ce484ff0bfcdb072e3a755aca6d6acc4bfe7e75a3972fbcaa4ae95588577d1c19ab82adc1cf4dc68239b931b40bb63d8a297ec9f106f8f1ec

test:
  secret_key_base: 784013c10eeb2c8bb1b3e75bfb7341dbe46d32c411369ea6343bf5e27973b9538cffe2cb51fe2beb37d40d4cc1d16975c043829c9b10b73413899fc995d33ebd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>